### ISSUE TITLE
Custom preferences not found

### ISSUE THREAD

**Issue by Perelandra0x309** [HaikuArchives/SuperPrefs#1]
Preferences in /boot/home/config/preferences are not displayed in the Custom Preferences box.  PulkoMandy suggests using BPathFinder class which is in the Storage Kit.  This will find all paths where preferences could be located.

**Comment by anirudhmurali** [comment]
Hi @Perelandra0x309, Thanks for posting. I pushed a commit (not the one referenced to this issue), SuperPrefs now uses 'B_PREFERENCES_DIRECTORY', 'B_USER_PREFERENCES_DIRECTORY', 'B_SYSTEM_PREFERENCES_DIRECTORY' to get preflets. Works fine from my end. Have also implemented prevention of multiple entries for the same preflet. And the Custom Preferences box is hidden when there's none to display. Please let me know if there's any issue still.

**Comment by Perelandra0x309** [comment]
Yes, this finds the preflet now.  Only it is named Einsteinium_Preferences which isn't the preflet name (it is just Einsteinium), are you using the signature for the label?

**Comment by anirudhmurali** [comment]
I'm using [GetLocalizedFileName](https://www.haiku-os.org/docs/api/classBLocaleRoster.html#a2fd434b841e208a139510c14679588b9) from the BLocaleRoster class. The [definition](http://xref.plausible.coop/source/xref/haiku/src/kits/locale/LocaleRoster.cpp#510) of this function seem to use the BCatalog's [GetString](https://www.haiku-os.org/docs/api/classBCatalog.html#a151e295bda9c5411fa0e2781f9f0653a) function. I'm using this, so that I can have localized preflet names. Should the catalog entry of Einsteinium_Preferences be changed to Einsteinium as both belong to same package?
